language: java

jdk:
  - openjdk11

addons:
  ssh_known_hosts: kotlin.link

before_script:
  - nvm install 10
  - yarn install

script:
  - ./gradlew check installDist

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: legacy

before_cache:
  - rm -f  "${HOME}/.gradle/caches/modules-2/modules-2.lock"
  - rm -rf "${HOME}/.gradle/caches/*/plugin-resolution/"
  - rm -rf "${HOME}/.gradle/caches/*/fileHashes/"
cache:
  yarn: true
  directories:
    - "${HOME}/.gradle/caches/"
    - "${HOME}/.gradle/wrapper/"

git:
  depth: 1
