language: java
os: linux
dist: bionic

jdk:
  - openjdk11

addons:
  ssh_known_hosts: kotlin.link

before_install:
  - nvm install 12

install:
  - yarn --cwd app-frontend install
  - ./gradlew assemble

script:
  #  - curl https://kotlin.link/api/readme > readme/README.adoc
  - ./gradlew check installDist
  - ./build/install/awesome-kotlin/bin/awesome-kotlin
  - yarn --cwd app-frontend run build
  - docker build -t "heapy/awesome:b${TRAVIS_BUILD_NUMBER}" -t "heapy/awesome:latest" ./app-backend/


deploy:
  - provider: script
    script: bash .ci/deploy-site.sh
    skip_cleanup: true
    on:
      branch: main
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    local_dir: readme
    target_branch: readme
    committer_from_gh: true
    on:
      branch: main

before_cache:
  - rm -f  "${HOME}/.gradle/caches/modules-2/modules-2.lock"
  - rm -rf "${HOME}/.gradle/caches/*/plugin-resolution/"
  - rm -rf "${HOME}/.gradle/caches/*/fileHashes/"
cache:
  yarn: true
  directories:
    - "${HOME}/.cache/awesome-kotlin/"
    - "${HOME}/.gradle/caches/"
    - "${HOME}/.gradle/wrapper/"

git:
  depth: 10
