language: node_js
node_js: 6
addons:
  ssh_known_hosts: kotlin.link
before_script:
  - npm test
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in deploy@morty.enc -out ~/.ssh/deploy@morty -d
  - chmod 600 ~/.ssh/deploy@morty
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/deploy@morty
script:
  - bash ./deploy.sh
cache:
  directories:
  - node_modules
